### ISSUE TITLE
Cannot run quick-start.sh on keystone-demo

### ISSUE THREAD

**Issue by graziadonghia** [keystone-enclave/keystone-demo#20]
Hello, I'm studying Keystone technology by following [this document](http://docs.keystone-enclave.org/en/latest/Getting-Started/index.html). I've already installed Keystone with qemu and I already tried it, everything was fine. 
However, when I try to un the keystone-demo with the script `quick-start.sh` I receive this error:
```
CMake Error at /keystone/sdk/build64/cmake/macros.cmake:89 (message):
  Don't know how to find runtime from current
  directory /keystone-demo
Call Stack (most recent call first):
 keystone/sdk/build64/cmake/macros.cmake:108 (get_runtime_dir)
  CMakeLists.txt:73 (add_eyrie_runtime)


-- Configuring incomplete, errors occurred!
```
I've checked the `keystone-demo/build/CMakeFiles/CMakeOutput.log` file but I couldn't find anything.
Thanks in advance!

**Comment by graziadonghia** [comment]
There was an issue with the cmake file, now everything works

**Comment by dayeol** [comment]
Hi @graziadonghia, sorry for the late reply!
Thank you for sharing your experience with keystone-demo.
What was the issue? Could you share how you fixed it?

**Comment by jmcol** [comment]
@dayeol, I'm facing the same problem. I built keystone in my `~/dev` directory by cloning `github.com/keystone-enclave/keystone` and then running the `fast-setup.sh` script. I was then able to run `keystone/build/scripts/run-quemu.sh` and then once inside the qemu instance, I successfully ran `insmod keystone-driver.ko` and `./tests.ke`. After that, I ran `make hash` in `~/dev/keystone/sm/` and successfully generated the `sm_expected_hash.h` file.

However, when I cloned the keystone-demo repository to my `~/dev` directory, and tried to run `SM_HASH=/home/jeff/dev/keystone/sm/tools/sm_expected_hash.h quick-start.sh` from my /home/dev/keystone-demo directory, I got the error described above. It appears as though the `get_runtime_dir` macro defined in `keystone/sdk/macros.cmake` gets confused when called from the separate keystone-demo directory, perhaps? Do you know how to fix this?

Thanks!

**Comment by jmcol** [comment]
@graziadonghia Did you resolve this problem? I'm having the same issue.
